# Generated by Django 4.0.2 on 2022-02-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_alter_event_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='highlighted',
        ),
    ]
