# Generated by Django 4.0.2 on 2022-02-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_owner_event_user_remove_event_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
