<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-16 16:27
=======
# Generated by Django 4.0.2 on 2022-03-15 15:47
>>>>>>> 2cead0aae3ffc40a0414783bf580e265f0b6775c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
