# Generated by Django 4.0.2 on 2022-03-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_time'),
        ('events', '0007_alter_event_created_by_alter_event_participants'),
    ]

    operations = [
    ]
