# Generated by Django 4.0.2 on 2022-03-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_created_by'),
        ('events', '0009_alter_event_created_by_alter_event_participants'),
    ]

    operations = [
    ]
