# Generated by Django 4.0.2 on 2022-02-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_rename_first_name_user_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='date_of_birth',
        ),
    ]
